"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import "./studio-workflow3.css";

type StoryOption = { id:string; title:string; slug:string; content_status:string };
type Episode = { id:string; episode_number:number; season_number:number; title:string; summary:string|null; episode_status:string; word_count:number|null; artwork_url:string|null };
type PlanningBlock = { id:string; episode_start:number; episode_end:number; title:string; arc_summary:string|null; content_status:string };
type Category = { slug:string; name:string; description:string|null; sort_order:number; record_count:number };
type CanonRecord = { id:string; slug:string; category:string; title:string; summary:string|null; description:string|null; content_status:string; is_public:boolean; spoiler_level:number; reveal_episode:{episode_number:number}|null; sections:{id:string;heading:string;content:string}[]; images:{id:string;public_url:string|null;alt_text:string|null;caption:string|null}[]; character_profile:Record<string,string|null>|null; related_records:{id:string;title:string;category:string;relationship_type:string}[]; linked_episodes:{id:string;episode_number:number;title:string;appearance_type:string}[] };
type Dashboard = { story:{id:string;title:string;content_status:string;short_description:string|null;description:string|null;cover_image_url:string|null}; premise:{premise_title:string;premise_text:string;content_status:string;version_number:number}|null; episodes:Episode[]; planning_blocks:PlanningBlock[]; canon_categories:Category[]; canon_records:CanonRecord[]; counts:{episodes:number;published_episodes:number;planning_blocks:number;canon_records:number} };

const tabs = ["Story Brief","Season Plan","Episodes","Canon","Planning","Review"] as const;
type Tab = typeof tabs[number];
const icons:Record<string,string> = { character:"♙",location:"△",organisation:"⚑",faction:"⚑",technology:"⚙",concept:"⚖",event:"⌛",artefact:"▣",object:"▣" };
const aliases:Record<string,string> = { character:"Characters",location:"Locations",organisation:"Factions",faction:"Factions",technology:"Technology & Science",concept:"Rules",event:"History & Timeline",artefact:"Objects",object:"Objects" };
const profileLabels:Record<string,string> = { role_in_story:"Role in the story",personality:"Personality",strengths:"Strengths",weaknesses:"Weaknesses",motivations:"Motivations",fears:"Fears",speech_style:"Speech style",appearance:"Appearance",habits_and_mannerisms:"Habits & mannerisms",moral_boundaries:"Moral boundaries",current_state:"Current state",character_arc_notes:"Development" };
const pretty = (v:string) => v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

function RichText({value}:{value:string}) {
  let plain=value;
  try { const doc=JSON.parse(value); if(doc?.content) plain=doc.content.map((n:any)=>n.content?.map((x:any)=>x.text??"").join("")??"").filter(Boolean).join("\n\n"); } catch {}
  const blocks=plain.split(/\n{2,}/).filter(Boolean);
  return <div className="w3-prose">{blocks.map((block,i)=>{const text=block.trim();const h=text.match(/^(#{1,3})\s+(.+)$/);if(h){const Tag=(h[1].length===1?"h2":h[1].length===2?"h3":"h4") as "h2";return <Tag key={i}>{h[2]}</Tag>}return <p key={i}>{text.replace(/\n/g," ")}</p>})}</div>;
}
function Empty({title,children}:{title:string;children:React.ReactNode}) { return <div className="w3-empty"><span>✦</span><h3>{title}</h3><p>{children}</p></div> }

export default function StudioWorkflow3Client(){
  const [stories,setStories]=useState<StoryOption[]>([]),[storyId,setStoryId]=useState(""),[data,setData]=useState<Dashboard|null>(null);
  const [tab,setTab]=useState<Tab>("Story Brief"),[mode,setMode]=useState<"studio"|"reference">("studio"),[theme,setTheme]=useState<"light"|"dark">("light");
  const [category,setCategory]=useState(""),[recordId,setRecordId]=useState(""),[episodeId,setEpisodeId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const saved=localStorage.getItem("story-studio-theme");if(saved==="dark")setTheme("dark");const initial=new URLSearchParams(location.search).get("story_id")??"";void supabase.rpc("list_studio_story_options",{p_studio_mode:true}).then(({data,error})=>{if(error){setError(error.message);setLoading(false);return}const list=(data??[]) as StoryOption[];setStories(list);setStoryId(list.some(s=>s.id===initial)?initial:list[0]?.id??"")})},[]);
  useEffect(()=>{if(!storyId)return;setLoading(true);setError("");const u=new URL(location.href);u.searchParams.set("story_id",storyId);history.replaceState({},"",u);void supabase.rpc("get_studio_story_dashboard",{p_story_id:storyId,p_studio_mode:mode==="studio"}).then(({data,error})=>{if(error)setError(error.message);else{const d=data as Dashboard;setData(d);setCategory(d.canon_categories.find(c=>c.record_count>0)?.slug??d.canon_categories[0]?.slug??"");setEpisodeId(d.episodes[0]?.id??"")}setLoading(false)})},[storyId,mode]);
  useEffect(()=>localStorage.setItem("story-studio-theme",theme),[theme]);
  const categories=data?.canon_categories??[];
  const records=useMemo(()=>(data?.canon_records??[]).filter(r=>r.category===category),[data,category]);
  const record=records.find(r=>r.id===recordId)??records[0]??null;
  const episode=data?.episodes.find(e=>e.id===episodeId)??data?.episodes[0]??null;
  useEffect(()=>{if(record&&record.id!==recordId)setRecordId(record.id)},[record,recordId]);
  return <main className={`w3-shell ${theme}`}>
    <header className="w3-header"><button className="w3-brand" onClick={()=>setTab("Story Brief")}><span className="w3-compass">✥</span><span><strong>Story Studio</strong><small>DISCOVER STORIES</small></span></button><nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="w3-actions"><select aria-label="Select story" value={storyId} onChange={e=>setStoryId(e.target.value)}>{stories.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><button onClick={()=>setMode(mode==="studio"?"reference":"studio")}>{mode==="studio"?"Studio":"Reference"}</button><button aria-label="Toggle theme" onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?"☾":"☀"}</button></div></header>
    {error&&<div className="w3-error">{error}</div>}{loading&&<div className="w3-loading">Opening the story studio…</div>}
    {!loading&&data&&<>
      {tab==="Story Brief"&&<section className="w3-page"><div className="w3-page-title"><div><p>STORY FOUNDATION</p><h1>Story Brief</h1></div><span>{pretty(data.story.content_status)}</span></div><article className="w3-brief">
        <div className="w3-wide-art">{data.story.cover_image_url?<img src={data.story.cover_image_url} alt=""/>:<div className="w3-art-empty"><span>✦</span><small>No story artwork is linked</small></div>}<div className="w3-art-caption"><span>THE WORLD OF</span><strong>{data.story.title}</strong></div></div>
        <div className="w3-brief-grid"><section><p className="w3-kicker">THE CONTROLLING IDEA</p><h2>{data.premise?.premise_title??data.story.title}</h2><p className="w3-lead">{data.story.short_description??data.story.description}</p><div className="w3-mini-rule"/>{data.premise?.premise_text?<RichText value={data.premise.premise_text}/>:<Empty title="No Story Brief loaded">Add the structured brief to the single premise text field.</Empty>}</section><aside>{["World","Conflict","Story engine","Tone"].map((x,i)=><div key={x}><span>{["✥","⚔","⚙","✎"][i]}</span><h3>{x}</h3><p>The Story Brief’s structured rich text supplies this production direction when the corresponding section is present.</p></div>)}</aside></div>
      </article></section>}
      {tab==="Season Plan"&&<section className="w3-page"><div className="w3-page-title"><div><p>STORY ARCHITECTURE</p><h1>Season Plan</h1></div><span>{data.planning_blocks.length} blocks</span></div><div className="w3-plan">{data.planning_blocks.length?data.planning_blocks.map((b,i)=><article key={b.id}><span>{String(i+1).padStart(2,"0")}</span><div><small>EPISODES {b.episode_start}–{b.episode_end}</small><h2>{b.title}</h2><p>{b.arc_summary??"No arc summary loaded."}</p></div><em>{pretty(b.content_status)}</em></article>):<Empty title="No season plan yet">Planning blocks will appear when loaded.</Empty>}</div></section>}
      {tab==="Episodes"&&<section className="w3-page"><div className="w3-page-title"><div><p>NARRATIVE</p><h1>Episodes</h1></div><span>{data.episodes.length} episodes</span></div><div className="w3-episodes"><aside>{data.episodes.map(e=><button key={e.id} className={episode?.id===e.id?"active":""} onClick={()=>setEpisodeId(e.id)}><span>{String(e.episode_number).padStart(2,"0")}</span><div><strong>{e.title}</strong><small>{pretty(e.episode_status)}</small></div></button>)}</aside><article>{episode?<><p className="w3-kicker">SEASON {episode.season_number} · EPISODE {episode.episode_number}</p><h2>{episode.title}</h2>{episode.artwork_url?<img src={episode.artwork_url} alt=""/>:<div className="w3-art-empty compact">No episode artwork linked</div>}<p className="w3-lead">{episode.summary??"No episode summary loaded."}</p><div className="w3-tags"><span>{pretty(episode.episode_status)}</span><span>{(episode.word_count??0).toLocaleString()} words</span></div></>:<Empty title="No episodes yet">Episode records will appear here.</Empty>}</article></div></section>}
      {tab==="Canon"&&<section className="w3-canon"><div className="w3-canon-nav"><button className={!category?"active":""}>Overview</button>{categories.map(c=><button key={c.slug} className={category===c.slug?"active":""} onClick={()=>{setCategory(c.slug);setRecordId("")}}><span>{icons[c.slug]??"✦"}</span>{aliases[c.slug]??c.name}<small>{c.record_count}</small></button>)}</div><div className="w3-page"><div className="w3-page-title canon"><div><p>THE AUTHORITATIVE WORLD REFERENCE</p><h1>{aliases[category]??pretty(category||"Canon")}</h1></div><span>{records.length} records</span></div>
        {!records.length?<Empty title="No Canon records in this category">No placeholder information has been invented.</Empty>:<div className="w3-canon-workspace"><aside>{records.map(r=><button key={r.id} className={record?.id===r.id?"active":""} onClick={()=>setRecordId(r.id)}>{r.images[0]?.public_url?<img src={r.images[0].public_url} alt=""/>:<span className="portrait">{icons[r.category]??"✦"}</span>}<div><strong>{r.title}</strong><small>{r.summary??"No summary loaded."}</small></div></button>)}</aside>{record&&<article className="w3-record"><div className="w3-record-hero"><div><p className="w3-kicker">{aliases[record.category]??pretty(record.category)} · {pretty(record.content_status)}</p><h2>{record.title}</h2><p className="w3-lead">{record.summary}</p><div className="w3-tags"><span>{record.is_public?"Public infrastructure":"Restricted"}</span>{record.reveal_episode&&<span>Reveals E{record.reveal_episode.episode_number}</span>}<span>Spoiler {record.spoiler_level}</span></div></div>{record.images[0]?.public_url?<img src={record.images[0].public_url} alt={record.images[0].alt_text??""}/>:<div className="w3-art-empty">No reference artwork linked</div>}</div>{record.description&&<section><h3>Overview</h3><p className="w3-lead">{record.description}</p></section>}{record.sections.map(s=><section key={s.id}><h3>{s.heading}</h3><RichText value={s.content}/></section>)}{record.character_profile&&<section><h3>Character reference</h3><div className="w3-attributes">{Object.entries(record.character_profile).filter(([k,v])=>profileLabels[k]&&v).map(([k,v])=><div key={k}><small>{profileLabels[k]}</small><p>{v}</p></div>)}</div></section>}{record.related_records.length>0&&<section><h3>Related Canon</h3><div className="w3-links">{record.related_records.map(r=><button key={r.id} onClick={()=>{setCategory(r.category);setRecordId(r.id)}}><small>{aliases[r.category]??pretty(r.category)}</small><strong>{r.title}</strong></button>)}</div></section>}{record.linked_episodes.length>0&&<section><h3>Linked episodes</h3><div className="w3-links">{record.linked_episodes.map(e=><button key={e.id} onClick={()=>{setEpisodeId(e.id);setTab("Episodes")}}><small>EPISODE {e.episode_number}</small><strong>{e.title}</strong></button>)}</div></section>}</article>}</div>}
      </div></section>}
      {tab==="Planning"&&<section className="w3-page"><div className="w3-page-title"><div><p>STUDIO WORKSPACE</p><h1>Planning</h1></div></div><Empty title="Planning remains available">No planning data beyond the Season Plan has been invented.</Empty></section>}
      {tab==="Review"&&<section className="w3-page"><div className="w3-page-title"><div><p>PRODUCTION EVIDENCE</p><h1>Review</h1></div></div><div className="w3-review">{[[data.counts.episodes,"Episodes"],[data.counts.published_episodes,"Published"],[data.counts.planning_blocks,"Plan blocks"],[data.counts.canon_records,"Canon records"]].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>}
    </>}
  </main>
}
